### ISSUE TITLE
CLI functions

### ISSUE THREAD

**Issue by anushkadesai077** [BigDataIA-Spring2023-Team-07/Assignment-03#9]
The fetchfile functions for NEXRAD were working well and were generating the correct link but we did not find functions synonymous to GOES18 bucket, which could have been incorporated as well

**Comment by shankar-dh** [comment]
According to the assignment, Piyush hadn't mentioned what necessary functions should be included for CLI. Since it's up to us, we included only NEXRAD. 

response from Piyush
<img width="568" alt="image" src="https://user-images.githubusercontent.com/114494327/226420220-779852e1-6199-481d-99d8-8c285ff73e43.png">
